---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feedback-on-mail
  annotations:
    gitlab.com/project-slug: 'app-dev-platform/backstage'
    servicenow.com/appcode: ONEP-003
    
spec:
  type: website
  lifecycle: experimental
  owner: user:redhat/yoswal
  system: system:devex/redhat-experience-platform
