---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feedback-on-jira
  annotations:
    jira/project-key: DEE           # 'jira-project-key' 

    feedback/type: 'JIRA'       # 'JIRA' | 'MAIL'
    feedback/host: 'https://issues.redhat.com'   # url of the service, it should be configured on backend as well, if not added the default 
    #                                            # host for the `feedback/type` will be used 
      
    # [required] if feedback/type is MAIL
    feedback/email-to: yoswal@redhat.com     # who to send the email  

spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
  profile:
    email: guest@example.com
