apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: development
spec:
  memberOf: [guests]
  profile:
    email: yashoswal18@gmail.com
    displayName: Yash Oswal
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  namespace: development
spec:
  type: team
  children: []
  members:
    - 'guest'
